[workspace]
members = [
  "lib/plants",
  "lib/database",
  "lib/html",
  "lib/pages",
  "lib/render_html",
  "render_static",
  "telegram_bot"
]
resolver = "2"
default-members = ["render_static","telegram_bot"]
