date_format = '%d.%m.%Y'
date_format_images = '%d%m%Y'

template_dir                   : str = 'html_templates'
species_overview_template_name : str = 'species_overview.html'
species_details_template_name  : str = 'species_details.html'
plant_overview_template_name   : str = 'plant_overview.html'
plant_details_template_name    : str = 'plant_details.html'
index_template_name            : str = 'index.html'
activity_log_template_name     : str = 'activity_logs.html'
header_template_name           : str = 'header.html'
footer_template_name           : str = 'footer.html'
graveyard_template_name        : str = 'graveyard.html'

out_dir               : str = 'html_out'
species_details_out   : str = 'plant_species'
plant_details_out     : str = 'plants'
species_overview_out  : str = 'species_overview.html'
plant_overview_out    : str = 'plant_overview.html'
index_out             : str = 'index.html'
activity_log_out      : str = 'activity_logs.html'
graveyard_out         : str = 'graveyard.html'

img_dir         : str = 'img'
img_species_dir : str = 'species'
img_plants_dir  : str = 'plants'
img_small_dir   : str = 'small'

species_dir             : str = 'PlantSpecies'
plants_dir              : str = 'Plants'
log_dir                 : str = 'Logs'
activity_log_file_name  : str = 'Activities.csv'
growth_log_file_name    : str = 'Growth.csv'
graveyard_file_name     : str = 'Graveyard.csv'

bot_dir                 : str = 'telegram_bot'
bot_config_name         : str = 'conf.json'
