name: Deploy Website
on: 
  push:
    branches:
      - main
jobs:
  htmlBuild:
    name: Publish Plants
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust 
        uses: hecrj/setup-rust-action@v2 
        with:
          rust-version: 1.85.0
      - name: Build Project 
        run: make website
      - name: Move Files
        run: |
          mv ./html_out ../public/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with: 
          folder: ../public
          branch: gh-pages
